name: 01 - Building Blocks

on: 
  push:
  pull_request:
  schedule:
    - cron: '*/5 * * * *'    
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello world!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Successful step
        run: |
          echo "I will succeed"
          exit 0
      - name: Say Goodfbye
        run: echo "Goodbye!"